services:
  app:
    build: .
    container_name: notuber
    ports:
      - '3000:3000'
    links:
      - mongo
    networks:
      - notuber-network
  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:4.4.25-ubi8-20240507T090501Z
    ports:
      - '27017:27017'
    volumes:
      - notuber:/data/db      
    networks:
      - notuber-network

volumes:
  notuber:

networks:
  notuber-network: